### ISSUE TITLE
Conversion of ilastik probabilities leads to "ndarray is not JSON serializable" 

### ISSUE THREAD

**Issue by joshmoore** [joshmoore/zarr-utils#1]
```
(zarr) /tmp $hdf2zarr B1_C1.tif_Probabilities.h5 B1_C1.Prob.Zarr
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zarr/bin/hdf2zarr", line 4, in <module>
    hdf2zarr()
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 95, in hdf2zarr
    hdf5_file.visititems(copy)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 565, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1641, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 564, in proxy
    return func(name, self[name])
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 93, in copy
    zarr_obj.attrs.update(obj.attrs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/attrs.py", line 123, in update
    self._write_op(self._update_nosync, *args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/attrs.py", line 77, in _write_op
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/attrs.py", line 134, in _update_nosync
    self._put_nosync(d)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/attrs.py", line 116, in _put_nosync
    self.store[self.key] = json_dumps(d)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/util.py", line 38, in json_dumps
    return json.dumps(o, indent=4, sort_keys=True, ensure_ascii=True,
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
(zarr) /tmp $h5ls -v B1_C1.tif_Probabilities.h5
Opened "B1_C1.tif_Probabilities.h5" with sec2 driver.
exported_data            Dataset {1/1, 236/236, 275/275, 271/271, 2/2}
    Attribute: axistags scalar
        Type:      variable-length null-terminated UTF-8 string
        Data:  "{\n  \"axes\": [\n    {\n      \"key\": \"t\",\n      \"typeFlags\": 8,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"z\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"y\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"x\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"c\",\n      \"typeFlags\": 1,\n      \"resolution\": 0,\n      \"description\": \"\"\n    }\n  ]\n}"
    Attribute: display_mode scalar
        Type:      variable-length null-terminated UTF-8 string
        Data:  "grayscale"
    Attribute: drange {2}
        Type:      native float
        Data:  0, 1
    Location:  1:800
    Links:     1
    Chunks:    {1, 50, 50, 51, 1} 510000 bytes
    Storage:   140703200 logical bytes, 183600000 allocated bytes, 76.64% utilization
    Type:      native float
```

**Comment by jakirkham** [comment]
In Numcodecs we have [`VLenUTF8`]( https://numcodecs.readthedocs.io/en/latest/vlen.html#numcodecs.vlen.VLenUTF8 ), which can be used to encode `str`s.

Though we've been thinking of this as an extension in v3. Probably more to unpack here. Issue ( https://github.com/zarr-developers/zarr-specs/issues/83 ) would be a good place for further discussion.

**Comment by joshmoore** [comment]
https://github.com/catalystneuro/HDF5Zarr suggested by @thewtex worked:

```
(hdf5zarr) /tmp/hdf5.zarr $cat ./exported_data/.zattrs
{
    "axistags": "{\n  \"axes\": [\n    {\n      \"key\": \"t\",\n      \"typeFlags\": 8,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"z\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"y\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"x\",\n      \"typeFlags\": 2,\n      \"resolution\": 0,\n      \"description\": \"\"\n    },\n    {\n      \"key\": \"c\",\n      \"typeFlags\": 1,\n      \"resolution\": 0,\n      \"description\": \"\"\n    }\n  ]\n}",
    "display_mode": "grayscale",
    "drange": [
        0.0,
        1.0
```
