### ISSUE TITLE
Conversion of ilastik image leads to "Unsupport HDF5 type"

### ISSUE THREAD

**Issue by joshmoore** [joshmoore/zarr-utils#2]
```
(zarr) /tmp $h5ls -v B1_C1.tif.h5
Opened "B1_C1.tif.h5" with sec2 driver.
__DATA_TYPES__           Group
    Location:  1:800
    Links:     1
data                     Dataset {1/Inf, 236/Inf, 275/Inf, 271/Inf, 2/Inf}
    Location:  1:2272
    Links:     1
    Chunks:    {1, 32, 32, 32, 1} 65536 bytes
    Storage:   70351600 logical bytes, 84934656 allocated bytes, 82.83% utilization
    Type:      native unsigned short
(zarr) /tmp $hdf2zarr B1_C1.tif.h5 B1_C1.zarr
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zarr/bin/hdf2zarr", line 4, in <module>
    hdf2zarr()
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 95, in hdf2zarr
    hdf5_file.visititems(copy)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 565, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1641, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 564, in proxy
    return func(name, self[name])
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 91, in copy
    assert False, "Unsupport HDF5 type."
AssertionError: Unsupport HDF5 type.
```

**Comment by jakirkham** [comment]
This one I'm less sure about. Could use some more context. `uint16` should be supported in Zarr `Array`s, but I'm unclear if that is the type we have issues with or if it is something else.
