### ISSUE TITLE
Conversion of BDV HDF5 leads to "zarr.errors.MetadataError: error decoding metadata: 0"

### ISSUE THREAD

**Issue by joshmoore** [joshmoore/zarr-utils#3]
```
(zarr) /opt/zarr-utils $hdf2zarr 081505_L1_bd5.h5 081505_L1_bd5.zarr/
[['ID', ['|S16', {'h5py_encoding': 'ascii'}]], ['fID', '<i4'], ['value', '<f4']]
['|S16', {'h5py_encoding': 'ascii'}]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 45, in decode_array_metadata
    dtype = decode_dtype(meta['dtype'])
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 105, in decode_dtype
    d = _decode_dtype_descr(d)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in _decode_dtype_descr
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in <listcomp>
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in _decode_dtype_descr
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in <listcomp>
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
KeyError: 0
END JOSH CHANGE IN META.PY
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 45, in decode_array_metadata
    dtype = decode_dtype(meta['dtype'])
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 105, in decode_dtype
    d = _decode_dtype_descr(d)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in _decode_dtype_descr
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in <listcomp>
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in _decode_dtype_descr
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 100, in <listcomp>
    d = [(k[0], _decode_dtype_descr(k[1])) + tuple(k[2:]) for k in d]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/zarr/bin/hdf2zarr", line 4, in <module>
    hdf2zarr()
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 95, in hdf2zarr
    hdf5_file.visititems(copy)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 565, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1641, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/h5py/_hl/group.py", line 564, in proxy
    return func(name, self[name])
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr_utils/__init__.py", line 89, in copy
    zarr_obj = root.create_dataset(name, data=obj, chunks=obj.chunks)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/hierarchy.py", line 770, in create_dataset
    return self._write_op(self._create_dataset_nosync, name, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/hierarchy.py", line 628, in _write_op
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/hierarchy.py", line 786, in _create_dataset_nosync
    a = array(data, store=self._store, path=path, chunk_store=self._chunk_store,
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/creation.py", line 341, in array
    z = create(**kwargs)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/creation.py", line 123, in create
    z = Array(store, path=path, chunk_store=chunk_store, synchronizer=synchronizer,
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/core.py", line 156, in _load_metadata_nosync
    meta = decode_array_metadata(meta_bytes)
  File "/usr/local/anaconda3/envs/zarr/lib/python3.8/site-packages/zarr/meta.py", line 61, in decode_array_metadata
    raise MetadataError('error decoding metadata: %s' % e)
zarr.errors.MetadataError: error decoding metadata: 0
(zarr) /opt/zarr-utils $h5ls -v 081505_L1_bd5.
081505_L1_bd5.h5    081505_L1_bd5.zarr/
(zarr) /opt/zarr-utils $h5ls -v 081505_L1_bd5.h5
Opened "081505_L1_bd5.h5" with sec2 driver.
data                     Group
    Location:  1:800
    Links:     1
```

**Comment by joshmoore** [comment]
You'll note in the output that I've edited the file. The second value debugged in:

```
[['ID', ['|S16', {'h5py_encoding': 'ascii'}]], ['fID', '<i4'], ['value', '<f4']]
['|S16', {'h5py_encoding': 'ascii'}]
```

has a flatter structure which leads to the exception.

**Comment by jakirkham** [comment]
So Zarr does support structured `dtype`s like this. Though I think the `{'h5py_encoding': 'ascii'}` bit is something special about `h5py` and how it handles encoding/decoding `unicode` to `bytes`. For example, one can construct a `dtype` like this with NumPy, which Zarr should also support. HTH

```python
np.dtype([('ID', '|S16'), ('fID', '<i4'), ('value', '<f4')])
```
